// <auto-generated />
namespace Depressed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Phase11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Phase11));
        
        string IMigrationMetadata.Id
        {
            get { return "202403230533436_Phase1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
